#!/usr/bin/env bash

set -Eeuo pipefail

readonly REPO_NAME="fedora-config"
readonly DOT_DIR="$HOME/.${REPO_NAME}"

log() {
  printf "\033[1;34m🚀 %s\033[0m\n" "$*"
}

error() {
  printf "\033[1;31m🔥 %s\033[0m\n" "$*" >&2
}

die() {
  error "$*"
  exit 1
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

fish_install() {
  log "Configuring fish shell..."

  log "Trashing existing config.fish...(use trash-restore to restore)"
  trash ~/.config/fish/config.fish || true

  log "Linking ($DOT_DIR/fish/config.fish) -> ($HOME/.config/fish/config.fish)"
  mkdir -p ~/.config/fish 2>/dev/null || true
  ln -sf "${DOT_DIR}/fish/config.fish" "${HOME}/.config/fish/config.fish"
}

dotfiles_install() {
  if [ ! -d "$DOT_DIR" ]; then
    has_cmd git || die "git is not installed. Quitting."
    log "Cloning dotfiles..."
    git clone https://github.com/pervezfunctor/fedora-config "$DOT_DIR" || die "git clone failed"
  fi
}

shell_install() {
  brew install nushell gdu shellcheck shfmt difftastic atuin bash-preexec direnv \
    duf dysk eza fd gh yq ripgrep bat starship tealdeer trash-cli ugrep zoxide
}

help() {
  local name
  name="$(basename "$0")"
  printf "\033[1;34m🚀 Usage: %s [command]...\033[0m\n" "$name"
  printf "\033[1;34m🚀\033[0m\n"
  printf "\033[1;34m🚀 Commands:\033[0m\n"
  printf "\033[1;34m🚀   dotfiles  - Clone dotfiles\033[0m\n"
  printf "\033[1;34m🚀   fish      - Install fish shell\033[0m\n"
  printf "\033[1;34m🚀   shell     - shell tools\033[0m\n"
  printf "\033[1;34m🚀\033[0m\n"
}

main() {
  export PATH="/home/linuxbrew/.linuxbrew/bin:$HOME/.pixi/bin:$PATH"

  if ! has_cmd ujust; then
    die "This script should be run only on ublue dx systems(Bluefin, Bazzite etc)"
  fi

  if [ ! $# -eq 0 ]; then
    case "$1" in
    help | --help | -h)
      help
      return
      ;;
    esac

    for arg in "$@"; do
      "${arg}_install" || true
    done
    return
  fi

  log "Bluefin Setup..."

  dotfiles_install
  fish_install
  shell_install

  log "╔══════════════════════════════════════╗"
  log "║   Bluefin Configuration complete.    ║"
  log "║   Use setup.nu for further config.   ║"
  log "╚══════════════════════════════════════╝"
}

main "$@"
