#!/bin/sh

set -eu

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

readonly REPO_URL="https://github.com/pervezfunctor/fedora-config.git"
readonly DOT_DIR="$HOME/.fedora-config"

log() {
  printf "INFO: %s\n" "$*"
  printf "INFO: %s\n" "$*" >>"${HOME}/.fedora-config.log"
}

warn() {
  printf "WARNING: %s\n" "$*"
  printf "WARNING: %s\n" "$*" >>"${HOME}/.fedora-config.log"
}

die() {
  printf "ERROR: %s\n" "$*" >&2
  printf "ERROR: %s\n" "$*" >>"${HOME}/.fedora-config.log"
  exit 1
}

dotfiles_install() {
  has_cmd git || die "git not found. Quitting."

  if [ ! -d "$DOT_DIR" ]; then
    log "Cloning dotfiles to $DOT_DIR."
    git clone "$REPO_URL" "$DOT_DIR" || die "Failed to clone $REPO_URL"
    return
  elif [ -z "$(git -C "$DOT_DIR" status --porcelain)" ]; then
    log "Dotfiles repo clean. Pulling latest changes"
    git -C "$DOT_DIR" pull --rebase || {
      warn "Rebase failed. Aborting."
      git -C "$DOT_DIR" rebase --abort || die "Failed to abort rebase"
    }
  else
    warn "Dotfiles repo dirty. Skipping update."
    return
  fi
}

system_install() {
  sudo dnf update -y || die "Failed to update packages"

  sudo dnf install -y git gcc pipx libatomic make plocate tar tmux unzip \
    zstd bat direnv duf eza fd fzf gdu gh jq ripgrep tealdeer trash-cli \
    zoxide difftastic less htop gum tmux

  tldr --update || die "Failed to install dependencies"

  sudo updatedb
}

pixi_install() {
  has_cmd pixi && return 0

  has_cmd curl || die "curl is not installed. Quitting."
  log "Installing pixi."
  curl -fsSL https://pixi.sh/install.sh | sh
  has_cmd pixi || die "Failed to install pixi"
}

pixi_packages_install() {
  pixi global install carapace nushell xh television starship bottom
}

fresh_install() {
  has_cmd dnf && system_install
  pixi_install
  pixi_packages_install
  dotfiles_install

  has_cmd nu || die "nu is not installed. Quitting."
  nu "${DOT_DIR}/scripts/setup.nu" fish 2>&1 | tee -a "${HOME}/.fedora-config.log"
}

has_commands() {
  for cmd in "$@"; do
    has_cmd "$cmd" || return 1
  done
  return 0
}

main() {
  rm -f "${HOME}/.fedora-config.log"
  touch "${HOME}/.fedora-config.log"

  export PATH="/home/linuxbrew/.linuxbrew/bin:$HOME/.pixi/bin:$PATH"

  if has_commands git pixi fish nu trash gh starship gum; then
    "${DOT_DIR}/scripts/setup.nu" 2>&1 | tee -a "${HOME}/.fedora-config.log"
  else
    fresh_install
  fi
}

main "$@"
