#!/usr/bin/env bash

set -Eeuo pipefail

readonly REPO_NAME="fedora-config"
readonly DOT_DIR="$HOME/.${REPO_NAME}"

log() {
  printf "\033[1;34m🚀 %s\033[0m\n" "$*"
}

error() {
  printf "\033[1;31m🔥 %s\033[0m\n" "$*" >&2
}

die() {
  error "$*"
  exit 1
}

has_cmd() {
  command -v "$1" >/dev/null 2>&1
}

system_install() {
  log "Updating packages..."
  sudo zypper refresh
  sudo zypper update

  log "Removing busybox..."
  sudo zypper remove -y busybox* || true
  sudo zypper remove -y busybox-less || true

  log "Installing packages..."
  local -a packages=(
    Catch2-devel
    ShellCheck
    bat
    boost-devel
    bottom
    clang
    clang-tools
    cmake
    coreutils
    curl
    difftastic
    duf
    dysk
    eza
    fd
    fish
    fzf
    gawk
    gcc16
    gcc16-c++
    gdu
    gh
    git
    grep
    htop
    jq
    less
    libc++-devel
    make
    ninja
    nushell
    python3-pipx
    python3-uv
    rclone
    ripgrep
    rsync
    sd
    sed
    shfmt
    starship
    tar
    tealdeer
    tmux
    trash-cli
    ugrep
    unzip
    watchexec
    wget
    xh
    yq
    zip
    zoxide
    zstd
  )

  sudo zypper install "${packages[@]}" || true
}

dotfiles_install() {
  if [ ! -d "$DOT_DIR" ]; then
    log "Cloning dotfiles repository..."
    has_cmd git || die "git is required but not installed"

    git clone https://github.com/pervezfunctor/fedora-config "$DOT_DIR" ||
      die "git clone failed"
  fi
}

fish_install() {
  log "Configuring fish shell..."

  log "Trashing existing config.fish...(use trash-restore to restore)"
  trash ~/.config/fish/config.fish || true

  log "Linking ($DOT_DIR/fish/config.fish) -> ($HOME/.config/fish/config.fish)"
  mkdir -p ~/.config/fish 2>/dev/null || true
  ln -sf "${DOT_DIR}/fish/config.fish" "${HOME}/.config/fish/config.fish"

  log "Setting fish as default shell..."
  if sudo chsh -s "$(which fish)" "$USER"; then
    log "Successfully set fish as default shell"
  else
    log "Failed to set fish as default shell"
    log "Run 'sudo chsh -s $(which fish) $USER' to set it manually"
  fi

  log "Installing carapace..."
  curl termux.carapace.sh | sh
}

docker_install() {
  sudo zypper install docker docker-docker-compose
  sudo systemctl enable docker.socket
  sudo systemctl start docker.socket
  sudo usermod -aG docker "$USER"
}

main() {
  has_cmd zypper || die "Only Tumbleweed is supported. Quitting."

  if [ ! $# -eq 0 ]; then
    for arg in "$@"; do
      "${arg}_install" || true
    done
    return
  fi

  log "Starting tumbleweed shell setup..."
  system_install
  dotfiles_install
  fish_install
  log "tumbleweed installation complete."
}

main "$@"
